name: Release
on:
  push:
    tags:
      - 'v*'  # Триггер на теги (v1.0.0, v2.3.0 и т.д.)

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: macos-latest
            name: macos
            ext: ""
          - os: windows-latest
            name: windows
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go build -o alertctl${{ matrix.ext }}
      - uses: actions/upload-artifact@v4
        with:
          name: alertctl-${{ matrix.name }}
          path: alertctl${{ matrix.ext }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: alertctl-*
          merge-multiple: true
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            alertctl-linux
            alertctl-macos
            alertctl-windows.exe