name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: macos-latest
            name: macos
            ext: ""
          - os: windows-latest
            name: windows
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go build -o alertctl${{ matrix.ext }}
      - uses: actions/upload-artifact@v4
        with:
          name: alertctl-${{ matrix.name }}
          path: alertctl${{ matrix.ext }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mv artifacts/alertctl-linux/alertctl* alertctl-linux || true
          mv artifacts/alertctl-macos/alertctl* alertctl-macos || true
          mv artifacts/alertctl-windows/alertctl* alertctl-windows.exe || true

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            alertctl-linux
            alertctl-macos
            alertctl-windows.exe
